export { RootScreen } from "./root/root.screen";
export { NotFoundScreen } from "./not-found/not-found.screen";
export { StartScreen } from "./start/start.screen"
export { HomeScreen } from "./home/home.screen";
export { HistoriaScreen } from "./historia/historia.screen";
export { CapitulosScreen } from "./capitulos/capitulos.screen";
export { AventuraScreen } from "./aventura/aventura.screen";
export { VersusScreen } from "./versus/versus.screen";
export { CosmosScreen } from "./cosmos/cosmos.screen";
export { LojaScreen } from "./loja/loja.screen";
export { PerfilScreen } from "./perfil/perfil.screen";
export { BatalhaScreen } from "./batalha/batalha.screen";