export { RootScreen } from "./root/root.screen";
export { NotFoundScreen } from "./not-found/not-found.screen";
export { StartScreen } from "./start/start.screen"
export { NovoJogoScreen } from "./novo-jogo/novo-jogo.screen"
export { HomeScreen } from "./home/home.screen";
export { HistoriaScreen } from "./historia/historia.screen";
export { CapitulosScreen } from "./capitulos/capitulos.screen";
export { AventuraScreen } from "./aventura/aventura.screen";
export { VersusScreen } from "./versus/versus.screen";
export { VersusPersonagensScreen } from "./versus-personagens/versus-personagens.screen";
export { VersusMapaScreen } from "./versus-mapas/versus-mapas.screen"
export { VersusBatalhaScreen } from "./versus-batalha/versus-batalha.screen"
export { CosmosScreen } from "./cosmos/cosmos.screen";
export { LojaScreen } from "./loja/loja.screen";
export { PerfilScreen } from "./perfil/perfil.screen";
export { BatalhaScreen } from "./batalha/batalha.screen";
export { CenaScreen } from "./cena/cena.screen"
export { JogarGachaScreen } from "./jogar-gacha/jogar-gacha.screen"
export { PerfilPersonagensScreen } from "./perfil-personagens/perfil-personagens.screen"
export { PersonagemDetalhadoScreen } from "./personagem-detalhado/personagem-detalhado.screen"
export { PersonagemEvoluirScreen } from "./personagem-evoluir/personagem-evoluir.screen"
export { PersonagemTalentosScreen } from "./personagem-talentos/personagem-talentos.screen"
export { PersonagemInventarioScreen } from "./personagem-inventario/personagem-inventario.screen"
export { PersonagemEquipamentosScreen } from "./personagem-equipamentos/personagem-equipamentos.screen"
export { PersonagemAcoesScreen } from "./personagem-acoes/personagem-acoes.screen"
export { PersonagemVisuaisScreen } from "./personagem-visuais/personagem-visuais.screen"