import { CONSUMIVEIS } from "../../itens/consumiveis"
import { EQUIPAMENTOS } from "../../itens/equipamentos"

export const equipamentosProntosData = [
        {
            id: 1,
            nome: "Nenhum",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [],
        },
        {
            id: 2,
            nome: "Kit de Combatente 3*",
            arma: EQUIPAMENTOS.ESPADA_FERRO.id,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
                {itemId: 3, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_SUPREMA.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_SUPREMO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO_MAIOR.id, quantidade: 1},
            ],
        },
        {
            id: 3,
            nome: "Kit de Combatente 4*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
            ],
        },
        {
            id: 4,
            nome: "Kit de Combatente 5*",
            arma: null,
            armadura: EQUIPAMENTOS.ARMADURA_DIVINA.id,
            acessorio1: EQUIPAMENTOS.ESCUDO_FERRO.id,
            acessorio2: EQUIPAMENTOS.ANEL_SERPENTE.id,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
                {itemId: 3, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_SUPREMA.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_SUPREMO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.TREVO_SORTE.id, quantidade: 1},
            ],
        },
        {
            id: 5,
            nome: "Kit de Atirador 3*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
            ],
        },
        {
            id: 6,
            nome: "Kit de Atirador 4*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
            ],
        },
        {
            id: 7,
            nome: "Kit de Atirador 5*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
                {itemId: 3, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_SUPREMA.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_SUPREMO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO_MAIOR.id, quantidade: 1},
            ],
        },
        {
            id: 8,
            nome: "Kit de Conjurador 3*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
            ],
        },
        {
            id: 9,
            nome: "Kit de Conjurador 4*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
            ],
        },
        {
            id: 10,
            nome: "Kit de Conjurador 5*",
            arma: null,
            armadura: null,
            acessorio1: null,
            acessorio2: null,
            consumiveis: [
                {itemId: 1, quantidade: 1},
                {itemId: 2, quantidade: 1},
                {itemId: 3, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.POCAO_MANA_SUPREMA.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MENOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_MAIOR.id, quantidade: 1},
                {itemId: CONSUMIVEIS.ELIXIR_SUPREMO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO.id, quantidade: 1},
                {itemId: CONSUMIVEIS.VENENO_MAIOR.id, quantidade: 1},
            ],
        },
    ]